-- Pub Bingo 0010: the 28-29 Sep 2026 research spreadsheet.
-- Run after 0009 (safe to re-run). Then re-run supabase/seed.sql, which adds the 20 new pubs, new drinks,
-- opening hours, events and research notes. This file only corrects rows that already exist, and only where
-- they still hold the value first seeded, so nothing an admin or visitor has changed is overwritten.
-- Generated once from the spreadsheet and the previous seed data; not regenerated by npm run seed:sql.

-- ---------------------------------------------------------------------------
-- Admin notes: up to 8000 characters (research notes grew past 4000).
-- ---------------------------------------------------------------------------
alter table public.pub_admin drop constraint if exists pub_admin_notes_check;
alter table public.pub_admin add constraint pub_admin_notes_check check (char_length(notes) <= 8000);

create or replace function public.admin_save_pub_admin(p_pub_id text, p_prices_online text, p_notes text, p_mark_checked boolean)
returns public.pub_admin
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.pub_admin;
begin
  if not public.is_admin() then
    raise exception 'Admins only' using errcode = '42501';
  end if;
  if coalesce(p_prices_online, 'unknown') not in ('yes', 'partial', 'no', 'unknown') then
    raise exception 'Prices online must be yes, partial, no or unknown';
  end if;
  if char_length(coalesce(p_notes, '')) > 8000 then
    raise exception 'Keep notes under 8000 characters';
  end if;
  insert into public.pub_admin (pub_id, prices_online, notes, prices_checked_at, updated_at)
  values (p_pub_id, coalesce(p_prices_online, 'unknown'), coalesce(p_notes, ''), case when p_mark_checked then now() end, now())
  on conflict (pub_id) do update set
    prices_online = excluded.prices_online,
    notes = excluded.notes,
    prices_checked_at = case when p_mark_checked then now() else public.pub_admin.prices_checked_at end,
    updated_at = now()
  returning * into v_row;
  return v_row;
end;
$$;

revoke execute on function public.admin_save_pub_admin(text, text, text, boolean) from public, anon;
grant execute on function public.admin_save_pub_admin(text, text, text, boolean) to authenticated;

-- ---------------------------------------------------------------------------
-- Pub details that changed (only where the live value is still the original seed value).
-- ---------------------------------------------------------------------------
update public.pubs set drinks_menu_url = 'https://www.theblueposts.net/drinks', updated_at = now() where id = 'the-blue-posts-berwick-street' and drinks_menu_url is not distinct from null;
update public.pubs set tags = array(select distinct unnest(tags || array['sing-along']::text[])) where id = 'the-blue-posts-berwick-street';
update public.pub_admin set prices_online = 'no', updated_at = now() where pub_id = 'the-blue-posts-berwick-street' and prices_online = 'unknown';
update public.pubs set food_menu_url = null, updated_at = now() where id = 'the-coach-and-horses' and food_menu_url is not distinct from 'https://www.greeneking.co.uk/pubs/greater-london/coach-and-horses-soho/menu';
update public.pubs set operator = 'Fuller''s', updated_at = now() where id = 'the-coach-and-horses' and operator is not distinct from 'Greene King';
update public.pub_admin set prices_online = 'no', updated_at = now() where pub_id = 'the-coach-and-horses' and prices_online = 'unknown';
update public.pub_admin set prices_online = 'yes', updated_at = now() where pub_id = 'the-dog-and-duck' and prices_online = 'unknown';
update public.pub_admin set prices_online = 'no', updated_at = now() where pub_id = 'the-toucan' and prices_online = 'unknown';
update public.pubs set drinks_menu_url = 'https://www.lambandflagcoventgarden.co.uk/drink', updated_at = now() where id = 'lamb-and-flag' and drinks_menu_url is not distinct from null;
update public.pubs set food_menu_url = 'https://www.lambandflagcoventgarden.co.uk/food/menus', updated_at = now() where id = 'lamb-and-flag' and food_menu_url is not distinct from null;
update public.pub_admin set prices_online = 'no', updated_at = now() where pub_id = 'lamb-and-flag' and prices_online = 'unknown';
update public.pubs set lat = 51.510389, updated_at = now() where id = 'the-coal-hole' and lat is not distinct from 51.51027;
update public.pubs set lng = -0.121297, updated_at = now() where id = 'the-coal-hole' and lng is not distinct from -0.12093;
update public.pub_admin set prices_online = 'yes', updated_at = now() where pub_id = 'the-coal-hole' and prices_online = 'unknown';
update public.pubs set operator = 'Independent', updated_at = now() where id = 'the-cross-keys' and operator is not distinct from 'Unknown (check)';
update public.pubs set drinks_menu_url = 'https://untappd.com/v/the-harp/43889', updated_at = now() where id = 'the-harp' and drinks_menu_url is not distinct from 'https://www.harpcoventgarden.com/drink';
update public.pub_admin set prices_online = 'no', updated_at = now() where pub_id = 'the-harp' and prices_online = 'unknown';
update public.pubs set opened_year = 2000, updated_at = now() where id = 'the-porterhouse' and opened_year is not distinct from null;
update public.pubs set food_menu_url = 'https://porterhouse.london/wp-content/uploads/2026/09/Autumn-Food-Menu-2026.pdf', updated_at = now() where id = 'the-porterhouse' and food_menu_url is not distinct from null;
update public.pubs set operator = 'Porterhouse Brewing Co. (independent)', updated_at = now() where id = 'the-porterhouse' and operator is not distinct from 'Porterhouse Brewing Co.';
update public.pubs set tags = array(select distinct unnest(tags || array['beer-garden']::text[])) where id = 'the-porterhouse';
update public.pubs set tags = array(select distinct unnest(tags || array['historic', 'dog-friendly']::text[])) where id = 'the-punch-and-judy';
update public.pub_admin set prices_online = 'partial', updated_at = now() where pub_id = 'the-punch-and-judy' and prices_online = 'unknown';
update public.pubs set tags = array(select distinct unnest(tags || array['dog-friendly']::text[])) where id = 'the-salisbury';
update public.pub_admin set prices_online = 'partial', updated_at = now() where pub_id = 'the-salisbury' and prices_online = 'unknown';
update public.pubs set drinks_menu_url = 'https://docs.google.com/presentation/d/1k7gRnKxP5BOVScO1blmw5zmYbGt7F2IK9LQq3ZySMH0/edit', updated_at = now() where id = 'the-craft-beer-co-holborn' and drinks_menu_url is not distinct from 'https://untappd.com/v/the-craft-beer-co/1608850/beers';
update public.pubs set tags = array(select distinct unnest(tags || array['sports-tv', 'live-music']::text[])) where id = 'the-craft-beer-co-holborn';
update public.pub_admin set prices_online = 'yes', updated_at = now() where pub_id = 'the-craft-beer-co-holborn' and prices_online = 'partial';
update public.pubs set drinks_menu_url = 'https://theshiptavern.co.uk/menus/drink-menu/', updated_at = now() where id = 'the-ship-tavern' and drinks_menu_url is not distinct from null;
update public.pubs set operator = 'Independent (Ev Inns; Heineken UK freehold)', updated_at = now() where id = 'the-ship-tavern' and operator is not distinct from 'Independent (Evans family)';
update public.pubs set tags = array(select distinct unnest(tags || array['sports-tv']::text[])) where id = 'the-ship-tavern';
update public.pubs set lat = 51.436926, updated_at = now() where id = 'the-alleyns-head' and lat is not distinct from 51.4359;
update public.pubs set lng = -0.088414, updated_at = now() where id = 'the-alleyns-head' and lng is not distinct from -0.0906;
update public.pubs set drinks_menu_url = 'https://www.emberinns.co.uk/nationalsearch/london/the-alleyns-head-west-dulwich/menus/drink', updated_at = now() where id = 'the-alleyns-head' and drinks_menu_url is not distinct from null;
update public.pub_admin set prices_online = 'yes', updated_at = now() where pub_id = 'the-alleyns-head' and prices_online = 'unknown';
update public.pubs set drinks_menu_url = 'https://www.therosendale.co.uk/assets/PAGE-1-SPRING-2026-1.pdf', updated_at = now() where id = 'the-rosendale' and drinks_menu_url is not distinct from 'https://www.therosendale.co.uk/menus/';
update public.pubs set lat = 51.449367, updated_at = now() where id = 'the-crown-and-greyhound' and lat is not distinct from 51.4488;
update public.pubs set drinks_menu_url = 'https://www.thecrownandgreyhound.co.uk/menus/drink', updated_at = now() where id = 'the-crown-and-greyhound' and drinks_menu_url is not distinct from null;
update public.pubs set food_menu_url = 'https://www.thecrownandgreyhound.co.uk/menus/food', updated_at = now() where id = 'the-crown-and-greyhound' and food_menu_url is not distinct from null;
update public.pubs set operator = 'Mitchells & Butlers (Castle)', updated_at = now() where id = 'the-crown-and-greyhound' and operator is not distinct from 'Innkeeper''s Collection (Mitchells & Butlers)';
update public.pub_admin set prices_online = 'yes', updated_at = now() where pub_id = 'the-crown-and-greyhound' and prices_online = 'unknown';
update public.pub_admin set prices_online = 'partial', updated_at = now() where pub_id = 'the-wood-house' and prices_online = 'unknown';

-- ---------------------------------------------------------------------------
-- Drinks: new prices for drinks already in the app (with a history entry), only where the live price is
-- still the original one. Estimates the research found aren't stocked any more are removed, unless
-- someone has reported a price for them.
-- ---------------------------------------------------------------------------
with changed as (update public.drinks set current_price = 8.05, source = 'website', source_url = 'https://www.nicholsonspubs.co.uk/restaurants/london/thedogandducksoholondon', category = 'Lager', volume_ml = null, last_updated_at = timestamptz '2026-09-28 12:00:00+01:00' where pub_id = 'the-dog-and-duck' and name_normalized = 'camden hells' and measure = 'pint' and current_price = 7.10 and source = 'seed' returning id, pub_id, name, category, measure, current_price, last_updated_at, source, source_url)
  insert into public.price_reports (pub_id, drink_id, drink_name, category, measure, price, reported_at, source, source_url)
  select pub_id, id, name, category, measure, current_price, last_updated_at, source, source_url from changed;
with changed as (update public.drinks set current_price = 7.75, source = 'website', source_url = 'https://www.nicholsonspubs.co.uk/restaurants/london/thedogandducksoholondon', category = 'Stout', volume_ml = null, last_updated_at = timestamptz '2026-09-28 12:00:00+01:00' where pub_id = 'the-dog-and-duck' and name_normalized = 'guinness' and measure = 'pint' and current_price = 6.90 and source = 'seed' returning id, pub_id, name, category, measure, current_price, last_updated_at, source, source_url)
  insert into public.price_reports (pub_id, drink_id, drink_name, category, measure, price, reported_at, source, source_url)
  select pub_id, id, name, category, measure, current_price, last_updated_at, source, source_url from changed;
with changed as (update public.drinks set current_price = 8.25, source = 'website', source_url = 'https://www.nicholsonspubs.co.uk/restaurants/london/thedogandducksoholondon', category = 'Pale Ale', volume_ml = null, last_updated_at = timestamptz '2026-09-28 12:00:00+01:00' where pub_id = 'the-dog-and-duck' and name_normalized = 'beavertown neck oil' and measure = 'pint' and current_price = 7.20 and source = 'seed' returning id, pub_id, name, category, measure, current_price, last_updated_at, source, source_url)
  insert into public.price_reports (pub_id, drink_id, drink_name, category, measure, price, reported_at, source, source_url)
  select pub_id, id, name, category, measure, current_price, last_updated_at, source, source_url from changed;
delete from public.drinks d where d.pub_id = 'the-dog-and-duck' and d.name_normalized = 'timothy taylor landlord' and d.measure = 'pint' and d.source = 'seed' and d.current_price = 6.40 and not exists (select 1 from public.price_reports r where r.drink_id = d.id and r.source <> 'seed');
delete from public.drinks d where d.pub_id = 'the-dog-and-duck' and d.name_normalized = 'thatchers gold' and d.measure = 'pint' and d.source = 'seed' and d.current_price = 6.80 and not exists (select 1 from public.price_reports r where r.drink_id = d.id and r.source <> 'seed');
update public.drinks set current_price = 6.00, source = 'seed', source_url = null, category = 'Stout', volume_ml = null, last_updated_at = now() where pub_id = 'the-toucan' and name_normalized = 'guinness' and measure = 'pint' and current_price = 6.30 and source = 'seed';
update public.drinks set current_price = 6.73, source = 'seed', source_url = null, category = 'Stout', volume_ml = null, last_updated_at = now() where pub_id = 'lamb-and-flag' and name_normalized = 'guinness' and measure = 'pint' and current_price = 6.80 and source = 'seed';
with changed as (update public.drinks set current_price = 7.70, source = 'website', source_url = 'https://www.nicholsonspubs.co.uk/restaurants/london/thecoalholestrandlondon', category = 'Lager', volume_ml = null, last_updated_at = timestamptz '2026-09-28 12:00:00+01:00' where pub_id = 'the-coal-hole' and name_normalized = 'madri excepcional' and measure = 'pint' and current_price = 7.30 and source = 'seed' returning id, pub_id, name, category, measure, current_price, last_updated_at, source, source_url)
  insert into public.price_reports (pub_id, drink_id, drink_name, category, measure, price, reported_at, source, source_url)
  select pub_id, id, name, category, measure, current_price, last_updated_at, source, source_url from changed;
with changed as (update public.drinks set current_price = 7.65, source = 'website', source_url = 'https://www.nicholsonspubs.co.uk/restaurants/london/thecoalholestrandlondon', category = 'Stout', volume_ml = null, last_updated_at = timestamptz '2026-09-28 12:00:00+01:00' where pub_id = 'the-coal-hole' and name_normalized = 'guinness' and measure = 'pint' and current_price = 7.00 and source = 'seed' returning id, pub_id, name, category, measure, current_price, last_updated_at, source, source_url)
  insert into public.price_reports (pub_id, drink_id, drink_name, category, measure, price, reported_at, source, source_url)
  select pub_id, id, name, category, measure, current_price, last_updated_at, source, source_url from changed;
delete from public.drinks d where d.pub_id = 'the-coal-hole' and d.name_normalized = 'fuller''s london pride' and d.measure = 'pint' and d.source = 'seed' and d.current_price = 6.60 and not exists (select 1 from public.price_reports r where r.drink_id = d.id and r.source <> 'seed');
delete from public.drinks d where d.pub_id = 'the-coal-hole' and d.name_normalized = 'camden pale ale' and d.measure = 'pint' and d.source = 'seed' and d.current_price = 7.10 and not exists (select 1 from public.price_reports r where r.drink_id = d.id and r.source <> 'seed');
delete from public.drinks d where d.pub_id = 'the-coal-hole' and d.name_normalized = 'aspall suffolk cyder' and d.measure = 'pint' and d.source = 'seed' and d.current_price = 6.90 and not exists (select 1 from public.price_reports r where r.drink_id = d.id and r.source <> 'seed');
delete from public.drinks d where d.pub_id = 'the-coal-hole' and d.name_normalized = 'blue moon' and d.measure = 'pint' and d.source = 'seed' and d.current_price = 7.40 and not exists (select 1 from public.price_reports r where r.drink_id = d.id and r.source <> 'seed');
update public.drinks set current_price = 5.90, source = 'seed', source_url = null, category = 'Real Ale', volume_ml = null, last_updated_at = now() where pub_id = 'the-harp' and name_normalized = 'dark star hophead' and measure = 'pint' and current_price = 5.90 and source = 'seed';
delete from public.drinks d where d.pub_id = 'the-harp' and d.name_normalized = 'fuller''s frontier' and d.measure = 'pint' and d.source = 'seed' and d.current_price = 6.70 and not exists (select 1 from public.price_reports r where r.drink_id = d.id and r.source <> 'seed');
delete from public.drinks d where d.pub_id = 'the-harp' and d.name_normalized = 'westons old rosie' and d.measure = 'pint' and d.source = 'seed' and d.current_price = 6.20 and not exists (select 1 from public.price_reports r where r.drink_id = d.id and r.source <> 'seed');
with changed as (update public.drinks set current_price = 7.30, source = 'website', source_url = 'https://porterhouse.london/wp-content/uploads/2026/04/QR-Code-Drinks-Menu-Spring-2026-Version-2.pdf', category = 'Stout', volume_ml = null, last_updated_at = timestamptz '2026-09-28 12:00:00+01:00' where pub_id = 'the-porterhouse' and name_normalized = 'porterhouse plain porter' and measure = 'pint' and current_price = 7.00 and source = 'seed' returning id, pub_id, name, category, measure, current_price, last_updated_at, source, source_url)
  insert into public.price_reports (pub_id, drink_id, drink_name, category, measure, price, reported_at, source, source_url)
  select pub_id, id, name, category, measure, current_price, last_updated_at, source, source_url from changed;
with changed as (update public.drinks set current_price = 7.40, source = 'website', source_url = 'https://porterhouse.london/wp-content/uploads/2026/04/QR-Code-Drinks-Menu-Spring-2026-Version-2.pdf', category = 'Stout', volume_ml = null, last_updated_at = timestamptz '2026-09-28 12:00:00+01:00' where pub_id = 'the-porterhouse' and name_normalized = 'porterhouse oyster stout' and measure = 'pint' and current_price = 7.20 and source = 'seed' returning id, pub_id, name, category, measure, current_price, last_updated_at, source, source_url)
  insert into public.price_reports (pub_id, drink_id, drink_name, category, measure, price, reported_at, source, source_url)
  select pub_id, id, name, category, measure, current_price, last_updated_at, source, source_url from changed;
delete from public.drinks d where d.pub_id = 'the-porterhouse' and d.name_normalized = 'porterhouse temple bräu' and d.measure = 'pint' and d.source = 'seed' and d.current_price = 7.10 and not exists (select 1 from public.price_reports r where r.drink_id = d.id and r.source <> 'seed');
delete from public.drinks d where d.pub_id = 'the-porterhouse' and d.name_normalized = 'porterhouse hop head' and d.measure = 'pint' and d.source = 'seed' and d.current_price = 7.40 and not exists (select 1 from public.price_reports r where r.drink_id = d.id and r.source <> 'seed');
delete from public.drinks d where d.pub_id = 'the-porterhouse' and d.name_normalized = 'stonewell cider' and d.measure = 'pint' and d.source = 'seed' and d.current_price = 7.10 and not exists (select 1 from public.price_reports r where r.drink_id = d.id and r.source <> 'seed');
update public.drinks set current_price = 6.95, source = 'seed', source_url = null, category = 'Stout', volume_ml = null, last_updated_at = now() where pub_id = 'the-punch-and-judy' and name_normalized = 'guinness' and measure = 'pint' and current_price = 7.30 and source = 'seed';
delete from public.drinks d where d.pub_id = 'the-craft-beer-co-holborn' and d.name_normalized = 'kernel table beer' and d.measure = 'pint' and d.source = 'seed' and d.current_price = 6.80 and not exists (select 1 from public.price_reports r where r.drink_id = d.id and r.source <> 'seed');
delete from public.drinks d where d.pub_id = 'the-craft-beer-co-holborn' and d.name_normalized = 'cloudwater ipa' and d.measure = 'pint' and d.source = 'seed' and d.current_price = 8.00 and not exists (select 1 from public.price_reports r where r.drink_id = d.id and r.source <> 'seed');
delete from public.drinks d where d.pub_id = 'the-craft-beer-co-holborn' and d.name_normalized = 'titanic plum porter' and d.measure = 'pint' and d.source = 'seed' and d.current_price = 6.90 and not exists (select 1 from public.price_reports r where r.drink_id = d.id and r.source <> 'seed');
delete from public.drinks d where d.pub_id = 'the-craft-beer-co-holborn' and d.name_normalized = 'lost & grounded keller pils' and d.measure = 'pint' and d.source = 'seed' and d.current_price = 7.40 and not exists (select 1 from public.price_reports r where r.drink_id = d.id and r.source <> 'seed');
delete from public.drinks d where d.pub_id = 'the-craft-beer-co-holborn' and d.name_normalized = 'oliver''s cider' and d.measure = 'pint' and d.source = 'seed' and d.current_price = 7.20 and not exists (select 1 from public.price_reports r where r.drink_id = d.id and r.source <> 'seed');
delete from public.drinks d where d.pub_id = 'the-craft-beer-co-holborn' and d.name_normalized = 'schneider weisse' and d.measure = 'pint' and d.source = 'seed' and d.current_price = 7.80 and not exists (select 1 from public.price_reports r where r.drink_id = d.id and r.source <> 'seed');
with changed as (update public.drinks set current_price = 5.90, source = 'website', source_url = 'https://www.therocketeustonroad.co.uk/drinks', category = 'Lager', volume_ml = 355, last_updated_at = timestamptz '2026-09-28 12:00:00+01:00' where pub_id = 'the-rocket' and name_normalized = 'modelo' and measure = 'bottle' and current_price = 6.10 and source = 'website' returning id, pub_id, name, category, measure, current_price, last_updated_at, source, source_url)
  insert into public.price_reports (pub_id, drink_id, drink_name, category, measure, price, reported_at, source, source_url)
  select pub_id, id, name, category, measure, current_price, last_updated_at, source, source_url from changed;
with changed as (update public.drinks set current_price = 5.85, source = 'website', source_url = 'https://www.therocketeustonroad.co.uk/drinks', category = 'Lager', volume_ml = 330, last_updated_at = timestamptz '2026-09-28 12:00:00+01:00' where pub_id = 'the-rocket' and name_normalized = 'peroni' and measure = 'bottle' and current_price = 6.05 and source = 'website' returning id, pub_id, name, category, measure, current_price, last_updated_at, source, source_url)
  insert into public.price_reports (pub_id, drink_id, drink_name, category, measure, price, reported_at, source, source_url)
  select pub_id, id, name, category, measure, current_price, last_updated_at, source, source_url from changed;
with changed as (update public.drinks set current_price = 5.85, source = 'website', source_url = 'https://www.therocketeustonroad.co.uk/drinks', category = 'Lager', volume_ml = 330, last_updated_at = timestamptz '2026-09-28 12:00:00+01:00' where pub_id = 'the-rocket' and name_normalized = 'corona' and measure = 'bottle' and current_price = 6.05 and source = 'website' returning id, pub_id, name, category, measure, current_price, last_updated_at, source, source_url)
  insert into public.price_reports (pub_id, drink_id, drink_name, category, measure, price, reported_at, source, source_url)
  select pub_id, id, name, category, measure, current_price, last_updated_at, source, source_url from changed;
with changed as (update public.drinks set current_price = 5.85, source = 'website', source_url = 'https://www.therocketeustonroad.co.uk/drinks', category = 'Lager', volume_ml = 330, last_updated_at = timestamptz '2026-09-28 12:00:00+01:00' where pub_id = 'the-rocket' and name_normalized = 'budweiser' and measure = 'bottle' and current_price = 6.05 and source = 'website' returning id, pub_id, name, category, measure, current_price, last_updated_at, source, source_url)
  insert into public.price_reports (pub_id, drink_id, drink_name, category, measure, price, reported_at, source, source_url)
  select pub_id, id, name, category, measure, current_price, last_updated_at, source, source_url from changed;
with changed as (update public.drinks set current_price = 6.10, source = 'website', source_url = 'https://www.therocketeustonroad.co.uk/drinks', category = 'Lager', volume_ml = 330, last_updated_at = timestamptz '2026-09-28 12:00:00+01:00' where pub_id = 'the-rocket' and name_normalized = 'desperados' and measure = 'bottle' and current_price = 6.30 and source = 'website' returning id, pub_id, name, category, measure, current_price, last_updated_at, source, source_url)
  insert into public.price_reports (pub_id, drink_id, drink_name, category, measure, price, reported_at, source, source_url)
  select pub_id, id, name, category, measure, current_price, last_updated_at, source, source_url from changed;
with changed as (update public.drinks set current_price = 5.85, source = 'website', source_url = 'https://www.therocketeustonroad.co.uk/drinks', category = 'Lager', volume_ml = 330, last_updated_at = timestamptz '2026-09-28 12:00:00+01:00' where pub_id = 'the-rocket' and name_normalized = 'daura damm (gluten free)' and measure = 'bottle' and current_price = 6.05 and source = 'website' returning id, pub_id, name, category, measure, current_price, last_updated_at, source, source_url)
  insert into public.price_reports (pub_id, drink_id, drink_name, category, measure, price, reported_at, source, source_url)
  select pub_id, id, name, category, measure, current_price, last_updated_at, source, source_url from changed;
with changed as (update public.drinks set current_price = 6.10, source = 'website', source_url = 'https://www.therocketeustonroad.co.uk/drinks', category = 'Wheat Beer', volume_ml = 500, last_updated_at = timestamptz '2026-09-28 12:00:00+01:00' where pub_id = 'the-rocket' and name_normalized = 'schöfferhofer grapefruit wheat beer' and measure = 'bottle' and current_price = 6.30 and source = 'website' returning id, pub_id, name, category, measure, current_price, last_updated_at, source, source_url)
  insert into public.price_reports (pub_id, drink_id, drink_name, category, measure, price, reported_at, source, source_url)
  select pub_id, id, name, category, measure, current_price, last_updated_at, source, source_url from changed;
with changed as (update public.drinks set current_price = 5.75, source = 'website', source_url = 'https://www.therocketeustonroad.co.uk/drinks', category = 'Other', volume_ml = 550, last_updated_at = timestamptz '2026-09-28 12:00:00+01:00' where pub_id = 'the-rocket' and name_normalized = 'newcastle brown ale' and measure = 'bottle' and current_price = 5.90 and source = 'website' returning id, pub_id, name, category, measure, current_price, last_updated_at, source, source_url)
  insert into public.price_reports (pub_id, drink_id, drink_name, category, measure, price, reported_at, source, source_url)
  select pub_id, id, name, category, measure, current_price, last_updated_at, source, source_url from changed;
with changed as (update public.drinks set current_price = 6.05, source = 'website', source_url = 'https://www.therocketeustonroad.co.uk/drinks', category = 'Pale Ale', volume_ml = null, last_updated_at = timestamptz '2026-09-28 12:00:00+01:00' where pub_id = 'the-rocket' and name_normalized = 'sharp''s atlantic pale ale' and measure = 'bottle' and current_price = 6.20 and source = 'website' returning id, pub_id, name, category, measure, current_price, last_updated_at, source, source_url)
  insert into public.price_reports (pub_id, drink_id, drink_name, category, measure, price, reported_at, source, source_url)
  select pub_id, id, name, category, measure, current_price, last_updated_at, source, source_url from changed;
with changed as (update public.drinks set current_price = 6.05, source = 'website', source_url = 'https://www.therocketeustonroad.co.uk/drinks', category = 'Other', volume_ml = 500, last_updated_at = timestamptz '2026-09-28 12:00:00+01:00' where pub_id = 'the-rocket' and name_normalized = 'sharp''s doom bar' and measure = 'bottle' and current_price = 6.20 and source = 'website' returning id, pub_id, name, category, measure, current_price, last_updated_at, source, source_url)
  insert into public.price_reports (pub_id, drink_id, drink_name, category, measure, price, reported_at, source, source_url)
  select pub_id, id, name, category, measure, current_price, last_updated_at, source, source_url from changed;
with changed as (update public.drinks set current_price = 6.10, source = 'website', source_url = 'https://www.therocketeustonroad.co.uk/drinks', category = 'Cider', volume_ml = 568, last_updated_at = timestamptz '2026-09-28 12:00:00+01:00' where pub_id = 'the-rocket' and name_normalized = 'magners original' and measure = 'bottle' and current_price = 6.25 and source = 'website' returning id, pub_id, name, category, measure, current_price, last_updated_at, source, source_url)
  insert into public.price_reports (pub_id, drink_id, drink_name, category, measure, price, reported_at, source, source_url)
  select pub_id, id, name, category, measure, current_price, last_updated_at, source, source_url from changed;
with changed as (update public.drinks set current_price = 6.60, source = 'website', source_url = 'https://www.therocketeustonroad.co.uk/drinks', category = 'Cider', volume_ml = 500, last_updated_at = timestamptz '2026-09-28 12:00:00+01:00' where pub_id = 'the-rocket' and name_normalized = 'thatchers haze' and measure = 'bottle' and current_price = 6.75 and source = 'website' returning id, pub_id, name, category, measure, current_price, last_updated_at, source, source_url)
  insert into public.price_reports (pub_id, drink_id, drink_name, category, measure, price, reported_at, source, source_url)
  select pub_id, id, name, category, measure, current_price, last_updated_at, source, source_url from changed;
with changed as (update public.drinks set current_price = 6.50, source = 'website', source_url = 'https://www.therocketeustonroad.co.uk/drinks', category = 'Cider', volume_ml = 500, last_updated_at = timestamptz '2026-09-28 12:00:00+01:00' where pub_id = 'the-rocket' and name_normalized = 'rekorderlig peach raspberry' and measure = 'bottle' and current_price = 6.70 and source = 'website' returning id, pub_id, name, category, measure, current_price, last_updated_at, source, source_url)
  insert into public.price_reports (pub_id, drink_id, drink_name, category, measure, price, reported_at, source, source_url)
  select pub_id, id, name, category, measure, current_price, last_updated_at, source, source_url from changed;
with changed as (update public.drinks set current_price = 6.50, source = 'website', source_url = 'https://www.therocketeustonroad.co.uk/drinks', category = 'Cider', volume_ml = 500, last_updated_at = timestamptz '2026-09-28 12:00:00+01:00' where pub_id = 'the-rocket' and name_normalized = 'rekorderlig strawberry lime' and measure = 'bottle' and current_price = 6.70 and source = 'website' returning id, pub_id, name, category, measure, current_price, last_updated_at, source, source_url)
  insert into public.price_reports (pub_id, drink_id, drink_name, category, measure, price, reported_at, source, source_url)
  select pub_id, id, name, category, measure, current_price, last_updated_at, source, source_url from changed;
with changed as (update public.drinks set current_price = 6.50, source = 'website', source_url = 'https://www.therocketeustonroad.co.uk/drinks', category = 'Cider', volume_ml = 500, last_updated_at = timestamptz '2026-09-28 12:00:00+01:00' where pub_id = 'the-rocket' and name_normalized = 'rekorderlig wild berries' and measure = 'bottle' and current_price = 6.70 and source = 'website' returning id, pub_id, name, category, measure, current_price, last_updated_at, source, source_url)
  insert into public.price_reports (pub_id, drink_id, drink_name, category, measure, price, reported_at, source, source_url)
  select pub_id, id, name, category, measure, current_price, last_updated_at, source, source_url from changed;
with changed as (update public.drinks set current_price = 6.05, source = 'website', source_url = 'https://www.emberinns.co.uk/nationalsearch/london/the-alleyns-head-west-dulwich/menus/drink', category = 'Stout', volume_ml = null, last_updated_at = timestamptz '2026-09-28 12:00:00+01:00' where pub_id = 'the-alleyns-head' and name_normalized = 'guinness' and measure = 'pint' and current_price = 6.50 and source = 'seed' returning id, pub_id, name, category, measure, current_price, last_updated_at, source, source_url)
  insert into public.price_reports (pub_id, drink_id, drink_name, category, measure, price, reported_at, source, source_url)
  select pub_id, id, name, category, measure, current_price, last_updated_at, source, source_url from changed;
with changed as (update public.drinks set current_price = 6.50, source = 'website', source_url = 'https://www.emberinns.co.uk/nationalsearch/london/the-alleyns-head-west-dulwich/menus/drink', category = 'Lager', volume_ml = null, last_updated_at = timestamptz '2026-09-28 12:00:00+01:00' where pub_id = 'the-alleyns-head' and name_normalized = 'madri' and measure = 'pint' and current_price = 6.60 and source = 'seed' returning id, pub_id, name, category, measure, current_price, last_updated_at, source, source_url)
  insert into public.price_reports (pub_id, drink_id, drink_name, category, measure, price, reported_at, source, source_url)
  select pub_id, id, name, category, measure, current_price, last_updated_at, source, source_url from changed;
delete from public.drinks d where d.pub_id = 'the-alleyns-head' and d.name_normalized = 'timothy taylor landlord' and d.measure = 'pint' and d.source = 'seed' and d.current_price = 5.95 and not exists (select 1 from public.price_reports r where r.drink_id = d.id and r.source <> 'seed');
with changed as (update public.drinks set current_price = 8.25, source = 'website', source_url = 'https://www.thecrownandgreyhound.co.uk/menus/drink', category = 'Pale Ale', volume_ml = null, last_updated_at = timestamptz '2026-09-28 12:00:00+01:00' where pub_id = 'the-crown-and-greyhound' and name_normalized = 'beavertown neck oil' and measure = 'pint' and current_price = 7.50 and source = 'seed' returning id, pub_id, name, category, measure, current_price, last_updated_at, source, source_url)
  insert into public.price_reports (pub_id, drink_id, drink_name, category, measure, price, reported_at, source, source_url)
  select pub_id, id, name, category, measure, current_price, last_updated_at, source, source_url from changed;
with changed as (update public.drinks set current_price = 8.20, source = 'website', source_url = 'https://www.thecrownandgreyhound.co.uk/menus/drink', category = 'Lager', volume_ml = null, last_updated_at = timestamptz '2026-09-28 12:00:00+01:00' where pub_id = 'the-crown-and-greyhound' and name_normalized = 'camden hells' and measure = 'pint' and current_price = 7.40 and source = 'seed' returning id, pub_id, name, category, measure, current_price, last_updated_at, source, source_url)
  insert into public.price_reports (pub_id, drink_id, drink_name, category, measure, price, reported_at, source, source_url)
  select pub_id, id, name, category, measure, current_price, last_updated_at, source, source_url from changed;
with changed as (update public.drinks set current_price = 7.80, source = 'website', source_url = 'https://www.thecrownandgreyhound.co.uk/menus/drink', category = 'Stout', volume_ml = null, last_updated_at = timestamptz '2026-09-28 12:00:00+01:00' where pub_id = 'the-crown-and-greyhound' and name_normalized = 'guinness' and measure = 'pint' and current_price = 7.20 and source = 'seed' returning id, pub_id, name, category, measure, current_price, last_updated_at, source, source_url)
  insert into public.price_reports (pub_id, drink_id, drink_name, category, measure, price, reported_at, source, source_url)
  select pub_id, id, name, category, measure, current_price, last_updated_at, source, source_url from changed;
